# Generated by Django 6.0.1 on 2026-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('category', models.CharField(choices=[('cake', 'Cake'), ('bread', 'Bread'), ('pastry', 'Pastry'), ('cookie', 'Cookie')], max_length=20)),
                ('image', models.ImageField(upload_to='products/')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
    ]
